# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='events_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='followers_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='following_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='gists_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='organizations_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='received_events_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='repos_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='starred_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='subscriptions_url',
            field=models.URLField(default='http://www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
