# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20161022_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='events_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='followers_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='following_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='gists_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='organizations_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='received_events_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='repos_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='starred_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='subscriptions_url',
        ),
        migrations.AddField(
            model_name='developer',
            name='url',
            field=models.URLField(default='www.test.com', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
