# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_auto_20161023_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='blog',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='github_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='github_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='hireable',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='public_gists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='public_repos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
