# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_auto_20161023_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='bio',
            field=models.CharField(blank=True, max_length=501, null=True),
        ),
    ]
