# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_auto_20161023_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_type', models.CharField(max_length=500)),
                ('public', models.BooleanField()),
                ('payload', models.TextField(blank=True, null=True)),
                ('repo_id', models.IntegerField(blank=True, null=True)),
                ('repo_name', models.CharField(blank=True, max_length=500, null=True)),
                ('repo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('gh_actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_login', models.CharField(max_length=200)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('org_login', models.CharField(blank=True, max_length=200, null=True)),
                ('gh_created_at', models.DateTimeField()),
                ('gh_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='github_created_at',
            new_name='gh_created_at',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='github_id',
            new_name='gh_id',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='user_type',
            new_name='gh_type',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='github_updated_at',
            new_name='gh_updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer'),
        ),
    ]
