# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0007_auto_20161023_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalPredictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(choices=[('CommitCommentEvent', 'CommitCommentEvent'), ('CreateEvent', 'CreateEvent'), ('DeleteEvent', 'DeleteEvent'), ('ForkEvent', 'ForkEvent'), ('GistEvent', 'GistEvent'), ('GollumEvent', 'GollumEvent'), ('IssueCommentEvent', 'IssueCommentEvent'), ('IssuesEvent', 'IssuesEvent'), ('MemberEvent', 'MemberEvent'), ('PublicEvent', 'PublicEvent'), ('PullRequestEvent', 'PullRequestEvent'), ('PullRequestReviewCommentEvent', 'PullRequestReviewCommentEvent'), ('PushEvent', 'PushEvent'), ('ReleaseEvent', 'ReleaseEvent'), ('WatchEvent', 'WatchEvent')], max_length=200)),
                ('formula', models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum')], max_length=200)),
                ('statistic', models.FloatField()),
                ('period', models.DateTimeField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
            ],
        ),
    ]
