# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0009_auto_20161024_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fork', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('homepage', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('stargazers_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('language', models.CharField(max_length=500)),
                ('has_issues', models.BooleanField()),
                ('has_downloads', models.BooleanField()),
                ('has_wiki', models.BooleanField()),
                ('has_pages', models.BooleanField()),
                ('forks_count', models.IntegerField()),
                ('mirror_url', models.CharField(blank=True, max_length=500, null=True)),
                ('open_issues_count', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('open_issues', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('default_branch', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
            ],
        ),
    ]
