# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0013_pullrequestevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='developers.Event'),
        ),
    ]
