# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0015_auto_20161026_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='self_referential',
            field=models.NullBooleanField(),
        ),
    ]
