# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0018_auto_20161026_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='repo_still_exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
