# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0020_auto_20161026_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='repo_still_exists',
            field=models.NullBooleanField(),
        ),
    ]
