# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0022_auto_20161027_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalpredictor',
            name='reference',
            field=models.CharField(choices=[('CommitCommentEvent', 'CommitCommentEvent'), ('CreateEvent', 'CreateEvent'), ('DeleteEvent', 'DeleteEvent'), ('ForkEvent', 'ForkEvent'), ('GistEvent', 'GistEvent'), ('GollumEvent', 'GollumEvent'), ('IssueCommentEvent', 'IssueCommentEvent'), ('IssuesEvent', 'IssuesEvent'), ('MemberEvent', 'MemberEvent'), ('PublicEvent', 'PublicEvent'), ('PullRequestEvent', 'PullRequestEvent'), ('PullRequestReviewCommentEvent', 'PullRequestReviewCommentEvent'), ('PushEvent', 'PushEvent'), ('ReleaseEvent', 'ReleaseEvent'), ('WatchEvent', 'WatchEvent'), ('QualityPROpened', 'QualityPROpened'), ('QualityPRClosed', 'QualityPRClosed')], max_length=200),
        ),
    ]
