# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0023_auto_20161027_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='original_repos',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='total_forks',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='total_stars',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
